# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f47dc2d33a010316b996ebe1f0048aa5599c94b42c5efa911f27ae86111c0d2394fba4ab2a4bef40074025e8f9537afc44cbf649d66b984fb1ce9914b8f4009a

test:
  secret_key_base: 00b2d0cdcce7d403ec7c39a7594a19cc530f110e67b2935f8d8ee4a12b39291f7fca5e31678047bacc756cd93f24ab60dd9342d1e39f321e03dee156f84e98f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
